spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://root:minhkha1606@localhost:27017/post-service?authSource=admin

server:
  port: 8083
  servlet:
    context-path: /post